<a href="https://colab.research.google.com/github/Tejaswisai-kamarajugadda/Pandas-Introduction-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Numpy - Numeric Python
# Most powerful package - Library

# Numpy - Dimensions

# A - One Dimensional Array
# [A,B] || [A
#           B] - Two Dimensional Array - Row || Column

# Three Dimensional

# Array - Storing, Manipulating, Similar Data type

# Faster than any mathematical functions
# convenient compared to other packages
# Memory efficiency
# Support multi dimensional arrays

# speed(Numpy operations) > speed(Lists operations)
# size(Numpy operations) < size(Lists operations)

In [2]:
# I[21/02, 9:05 am] Sarada Clg: # Creating 2D array - Matrix
arr2D = np.array([
    [1,2,3],[4,5,6]
])
print(arr2D)
[21/02, 9:05 am] Sarada Clg: # Creating arrays with default values

# Creating matrix with all values of elements as '0'
allZeros = np.zeros((2,3))
print(allZeros)

# Creating matrix with all values of elements as '1'
allOnes = np.ones((2,3))
print(allOnes)

# Creating matrix with all values of elements as 'constant value- n ~ Fill value'
allConstant = np.full((2,3),6)
print(allConstant)
[21/02, 9:07 am] Sarada Clg: # Create an identity matrix - I - Square matrix

identity = np.eye(4)
print(identity)

# Identity Matrix - Aii = 1 && Aij = 0
# For all A Belongs to R M×N
# Aijnstall numpy _ pip3 install numpy // pip install numpy

In [5]:
import numpy as np

In [6]:
# Create a numpy array
# 1D array

arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [7]:
# Creating 2D array - Matrix
arr2D = np.array([
    [1,2,3],[4,5,6]
])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [8]:
# Creating arrays with default values

# Creating matrix with all values of elements as '0'
allZeros = np.zeros((2,3))
print(allZeros)

# Creating matrix with all values of elements as '1'
allOnes = np.ones((2,3))
print(allOnes)

# Creating matrix with all values of elements as 'constant value- n ~ Fill value'
allConstant = np.full((2,3),6)
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [9]:
# Create an identity matrix - I - Square matrix

identity = np.eye(4)
print(identity)

# Identity Matrix - Aii = 1 && Aij = 0
# For all A Belongs to R M×N
# Aij

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
# Creating random Matrices

# between 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

# between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.31716407 0.69037369 0.49667989]
 [0.43024185 0.57802852 0.10660487]
 [0.76737987 0.69919424 0.36181055]]
[[10 19 17]
 [14 16 19]
 [17 11 19]]


In [11]:
# Array Properties

arr = np.array([[1,2,3,4],[2,3,4,5]])
print(arr)

# Shape or array
print(f'\nThe shape of the array is {arr.shape}')

# Size of array
print(f'The size of the array is {arr.size}')

# Datatype of array
print(f'The Data type of the array is {arr.dtype}')

# Dimensions of array
print(f'The Dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]

The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimension of the array is 2


In [12]:
# Indexing and Slicing

# Access the elements in 1D Array
arr = np.array([1,2,3,4])
print(arr)
print(arr[3])

# Slicing the elements
print(arr[0:3])
# Indexing and Slicing

# Slicing the elements
print(arr[0:3])

# Access the element in 2D Array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:]) # first row with all columns
print(arr2[:,0]) # first Column with all rows

[1 2 3 4]
4
[1 2 3]
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [13]:
# L1 = []
# [L1.append(_) for _ in range(10)]

L1 = np.arange(10,-10,-1)

print(L1)

[10  9  8  7  6  5  4  3  2  1  0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [14]:
# Mathematical operations

a = np.array([1,2,3])
b = np.array([3,4,5])

print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [15]:
# Matrix multiplication
b1 = np.array([[1,2,3],[2,3,4]])
b2 = np.array([[5,6],[7,8],[1,3]])

# Dot product __ product=AB __ A m × n __ B n × p
c = np.dot(b1,b2)
print(c)

[[22 31]
 [35 48]]


In [16]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [17]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [18]:
[
   [22,31],
   [35,48]
]

[[22, 31], [35, 48]]